/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export {}
declare global {
  const sharedKernelD: typeof import('./shared-kernel/shared-kernel.d')['default']
}
